- 3rd-study/week01/danc/BOJ10828_Stack.java
- 3rd-study/week01/danc/BOJ11866_Josephus.java
- 3rd-study/week01/danc/BOJ14425_StringSet.java
- 3rd-study/week01/danc/BOJ2748_Fibonacci2.java
- 3rd-study/week01/danc/BOJ2839_Deliver_Sugar.java
BOJ 2748 피보나치 수 : DP
BOJ 2839 설탕 배달 : Greedy 
BOJ 10828 스택 : ArrayList 
BOJ 11866 요세푸스 : Queue
BOJ 14425 문자열 집합: HashMap
> danc: week01

- 3rd-study/week01/yeonkkk/Bj10828.java
- 3rd-study/week01/yeonkkk/Bj11866.java
- 3rd-study/week01/yeonkkk/Bj14425.java
- 3rd-study/week01/yeonkkk/Bj2748.java
- 3rd-study/week01/yeonkkk/Bj2839.java
BOJ 2839 설탕 배달 : 그리디
BOJ 14425 문자열 집합 : 리스트, 문자열
BOJ 10828 스택 : 스택
BOJ 11866 요세푸스 문제 0 : 큐
BOJ 2748 피보나치 수 2 : DP
> Yeonkkk: week01

- 3rd-study/week02/BOJ10816_NumCard2.java
- 3rd-study/week02/BOJ10845_Queue1.java
- 3rd-study/week02/BOJ11047_Coin0.java
- 3rd-study/week02/BOJ11652_Card.java
- 3rd-study/week02/BOJ7568_Body.java
BOJ7568: 완전탐색
BOJ10816 :  이진 탐색
BOJ10845 : 큐
BOJ11047 : 그리디
BOJ11652 : 해시맵
> danc: week02

- 3rd-study/week02/Damgom/Boj_10816.java
- 3rd-study/week02/Damgom/Boj_10845.java
- 3rd-study/week02/Damgom/Boj_11047.java
- 3rd-study/week02/Damgom/Boj_11652.java
- 3rd-study/week02/Damgom/Boj_7568.java
boj_10845 : 큐
boj_10816 : 해시맵
boj_11047 : 그리디알고리즘
boj_7568 : 완전탐색
boj_11652 : 해시
> Damgom: week02

- 3rd-study/week02/yeonkkk/Bj10816.java
- 3rd-study/week02/yeonkkk/Bj10845.java
- 3rd-study/week02/yeonkkk/Bj11047.java
- 3rd-study/week02/yeonkkk/Bj11652.java
- 3rd-study/week02/yeonkkk/Bj7568.java
BOJ 10845 큐: Deque
BOJ 10816 숫자 카드 2: HashMap
BOJ 11047 동전 0: 그리디
BOJ 7568 덩치: 완전탐색(브루트포스) 알고리즘
BOJ 11652 카드: HashMap
<br>
<br>
[[Java(자바)] Deque(덱/데크) 자료구조](https://soft.plusblog.co.kr/24)
> Yeonkkk: week02

- 3rd-study/week03/Damgom/Boj_10866.java
- 3rd-study/week03/Damgom/Boj_1920.java
- 3rd-study/week03/Damgom/Boj_2606.java
- 3rd-study/week03/Damgom/Boj_2751.java
- 3rd-study/week03/Damgom/Boj_4673.java
* Boj_4673 셀프 넘버 - 완전탐색
* Boj_2606 바이러스 - dfs
* Boj_1920 수 찾기 - 이분탐색
* Boj_10866 덱 - 덱
* Boj_2751 수 정렬하기 2 - 정렬
그림으로 보는 dfs
> Damgom: week03

- 3rd-study/week03/BOJ10866_Deque.java
- 3rd-study/week03/BOJ1920_FindNum.java
- 3rd-study/week03/BOJ2606_Virus.java
- 3rd-study/week03/BOJ2751_SortNum2.java
- 3rd-study/week03/BOJ4673_SelfNum.java
BOJ 1920. 수 찾기: 이진 탐색
BOJ 2606. 바이러스: Graph(행렬) - DFS 
BOJ 2751. 수 정렬하기 2: 정렬 (Collections.sort())
BOJ 4673. 셀프 넘버:  ?? (풀었는데 어떤 카테고리에 들어가는지 모르겠습니다) 
BOJ 10866.  덱: Deque
> danc: week03

- 3rd-study/week02/yeonkkk/Bj10816.java
- 3rd-study/week02/yeonkkk/Bj10845.java
- 3rd-study/week02/yeonkkk/Bj11047.java
- 3rd-study/week02/yeonkkk/Bj11652.java
- 3rd-study/week02/yeonkkk/Bj7568.java
- 3rd-study/week03/yeonkkk/Bj10866.java
- 3rd-study/week03/yeonkkk/Bj1920.java
- 3rd-study/week03/yeonkkk/Bj2606.java
- 3rd-study/week03/yeonkkk/Bj2751.java
- 3rd-study/week03/yeonkkk/Bj4673.java
* BOJ 10866. 덱: deque
* BOJ 1920. 수 찾기: 이진탐색
* BOJ 2606. 바이러스: 그래프, dfs, map
* BOJ 2751. 수 정렬하기 2: 정렬
* BOJ 4673. 셀프 넘버: 완전 탐색
<br>
<br>
* [[알고리즘] 이분 탐색 / 이진 탐색 (Binary Search)](https://velog.io/@kimdukbae/%EC%9D%B4%EB%B6%84-%ED%83%90%EC%83%89-%EC%9D%B4%EC%A7%84-%ED%83%90%EC%83%89-Binary-Search)
* [Arrays.binarySearch() 메소드](https://bang2001.tistory.com/12)
* [[Algorithm] DFS (Depth-first Search)를 Java로 구현해보자!](https://codingnojam.tistory.com/44)
> Yeonkkk: week03

- 3rd-study/week04/Damgom/Boj_11399.java
- 3rd-study/week04/Damgom/Boj_11726.java
- 3rd-study/week04/Damgom/Boj_1620.java
- 3rd-study/week04/Damgom/Boj_24479.java
- 3rd-study/week04/Damgom/Boj_9012.java
* boj_11399 ATM : 정렬, 그리디
* boj_11726 2 x n 타일링 : dp
* boj_1620 나는야 포켓몬 마스터 이다솜 : 해쉬
* boj_9012 괄호 : 스택
* boj_24479 : graph, dfs
> Damgom: Week04

- 3rd-study/week04/yeonkkk/Boj11399.java
- 3rd-study/week04/yeonkkk/Boj11726.java
- 3rd-study/week04/yeonkkk/Boj1620.java
- 3rd-study/week04/yeonkkk/Boj24479.java
- 3rd-study/week04/yeonkkk/Boj9012.java
BOJ 11399. ATM : 정렬, 그리디
BOJ 11726. 2 x n 타일링 : dp
BOJ 1620. 나는야 포켓몬 마스터 이다솜 : hashmap
BOJ 9012. 괄호 : stack
BOJ 24479. 알고리즘 수업 - 깊이 우선 탐색 1: graph, dfs(stack)
> Yeonkkk: week04

- 3rd-study/week03/tkdtn1427/덱_10866.java
- 3rd-study/week03/tkdtn1427/바이러스_2606.java
- 3rd-study/week03/tkdtn1427/셀프넘버_4673.java
- 3rd-study/week03/tkdtn1427/수정렬하기2_2751.java
- 3rd-study/week03/tkdtn1427/수찾기_1920.java
> 간단하게 작성해주세요. 아래 예시 참고
* BOJ 1111. 길찾기: 자료구조 스택 이용
* BOJ 1234. 거스름돈: 그리디  
<br>
<br>
> 질문이 있을 때만 작성하시고 없을 땐 이 부분 지워주시면 될 것 같습니다.
* BOJ 2334 문제 계속 틀리네요. 이 부분이 이상한데 어디가 문제인지 모르겠습니다.
```java
의심 스러운 부분, 모르겠으면 코드 전체
```
<br>
<br>
> 공부하면서 참고한 자료 링크 걸어주세요. 없으면 이 부분 지워주세요.
* [링크1](https://www.google.com)
> week3 : sol

- 3rd-study/week05/Damgom/Boj_10610.java
- 3rd-study/week05/Damgom/Boj_11650.java
- 3rd-study/week05/Damgom/Boj_1260.java
- 3rd-study/week05/Damgom/Boj_1874.java
- 3rd-study/week05/Damgom/Boj_9095.java
* Boj_1874. 스택 수열 : stack
* Boj_9095 1, 2, 3 더하기 : dp
* Boj_1260 dfs와 bfs
* Boj_11650 좌표 정렬하기 : 정렬
* Boj_10610 30 : 그리디, 정렬, 구현
> Damgom: week05

- 3rd-study/week05/danc/BOJ10610_30.java
- 3rd-study/week05/danc/BOJ11650_SortingMatrix.java
- 3rd-study/week05/danc/BOJ1260_DFSnBFS.java
- 3rd-study/week05/danc/BOJ1874_Stack_NumSequence.java
- 3rd-study/week05/danc/BOJ9095_SumOf123.java
BOJ1260 DFS와BFS
BOJ1874 스택수열 : 스택 
BOJ9095 1,2,3 더하기 : Dynamic Programming
BOJ10610 30 :  그리디
BOJ11650 좌표 정렬하기: 정렬 (Arrays.sort에서 Comporator를 오버라이팅 해서 사용)
> danc: week05

- 3rd-study/week05/yeonkkk/Boj10610.java
- 3rd-study/week05/yeonkkk/Boj11650.java
- 3rd-study/week05/yeonkkk/Boj1260.java
- 3rd-study/week05/yeonkkk/Boj1874.java
- 3rd-study/week05/yeonkkk/Boj9095.java
BOJ1260. DFS와BFS: dfs, bfs (stack, queue)
BOJ1874. 스택수열 : stack
BOJ9095. 1,2,3 더하기 : DP
BOJ10610. 30 : 그리디
BOJ11650. 좌표 정렬하기: 정렬 
<br>
<br>
BOJ 1260 DFS와 BFS 문제를 백준에서 채점하면 `nullPointer` 에러가 발생합니다.  
인텔리제이에서는 문제가 발생을 안하고, 반례 케이스들을 찾아서 넣어봐도 딱히 에러가 안나서 질문드립니다.  
어디서 에러가나는 것인지 모르겠습니다..  
참고한 [반례 모음집](https://www.acmicpc.net/board/view/24356) 입니다.
<br>
<br>
* [[백준,BOJ 9095] 1, 2, 3 더하기( JAVA 구현)](https://fbtmdwhd33.tistory.com/73)
* [[Java] 객체 정렬하기 1부 - Comparable vs Comparator](https://www.daleseo.com/java-comparable-comparator/)
* [(JAVA) 백준 10610번 : 30 --- [문자열]](https://maivve.tistory.com/289)
> Yeonkkk: week05

- 3rd-study/week05/DFS와BFS_1260.java
- 3rd-study/week05/_123더하기_9095.java
- 3rd-study/week05/_30_10610.java
- 3rd-study/week05/스택수열_1874.java
- 3rd-study/week05/좌표정렬하기_11650.java
> 간단하게 작성해주세요. 아래 예시 참고
* BOJ 1111. 길찾기: 자료구조 스택 이용
* BOJ 1234. 거스름돈: 그리디  
<br>
<br>
> 질문이 있을 때만 작성하시고 없을 땐 이 부분 지워주시면 될 것 같습니다.
* BOJ 2334 문제 계속 틀리네요. 이 부분이 이상한데 어디가 문제인지 모르겠습니다.
```java
의심 스러운 부분, 모르겠으면 코드 전체
```
<br>
<br>
> 공부하면서 참고한 자료 링크 걸어주세요. 없으면 이 부분 지워주세요.
* [링크1](https://www.google.com)
> week05 : tkdtn1427

- 3rd-study/week06/Damgom/Boj_11053.java
- 3rd-study/week06/Damgom/Boj_1182.java
- 3rd-study/week06/Damgom/Boj_16953.java
- 3rd-study/week06/Damgom/Boj_1966.java
- 3rd-study/week06/Damgom/Boj_3085.java
- 3rd-study/week07/Damgom/Boj_1205.java
- 3rd-study/week07/Damgom/Boj_13305.java
- 3rd-study/week07/Damgom/Boj_1748.java
* boj_16953, A → B , greedy
* boj_1182, 부분수열의 합, dfs 백트래킹
* boj_1966, 프린터 큐, Queue 구현
* boj_11053, 가장 긴 증가하는 부분 수열, dp
* boj_3085, 사탕 게임, 완전탐색 구현
<br>
<br>
> Damgom: week06

- 3rd-study/week08/Damgom/Boj_1138.java
- 3rd-study/week08/Damgom/Boj_1213.java
- 3rd-study/week08/Damgom/Boj_2477.java
* Boj_1138 한 줄로 서기 : 구현
* Boj_1213 팰린드롬 만들기 : 구현 그리디 문자열
* Boj_2477 참외밭 : 구현 기하학
> Damgom: week08 solve

- 3rd-study/week09/Damgom/Boj_1063.java
- 3rd-study/week09/Damgom/Boj_2002.java
- 3rd-study/week09/Damgom/Boj_21921.java
- 3rd-study/week09/Damgom/Boj_2607.java
* Boj_2607 비슷한 단어 : 구현, 문자열
* Boj_21921 블로그 : 구현, 누적합, 슬라이딩윈도우
* Boj_2002 추월 : 구현, 해시
* Boj_1063 킹 : 구현, 시뮬레이션
> Damgom: week09 solve

- 3rd-study/week09/yeonkkk/Boj1063.java
- 3rd-study/week09/yeonkkk/Boj2607.java
* BOJ 1063. 킹: 구현
* BOJ 1234. 2607 비슷한 단어:  구현, 리스트
<br>
커밋 메시지를 잘못 작성했습니다.  
실제로 푼 문제는 위와 같습니다.
> Yeonkkk: week09

- 3rd-study/week10/yeonkkk/Boj15565.java
- 3rd-study/week10/yeonkkk/Boj2002.java
- 3rd-study/week10/yeonkkk/Boj21921.java
- 3rd-study/week10/yeonkkk/Boj22233.java
* BOJ 15565. 귀여운 라이언: 인덱스, 슬라이딩 윈도우
* BOJ 22233. 가희와 키워드: HashMap
* BOJ 21921. 블로그: 누적합, 슬라이딩 윈도우
* BOJ 2002. 추월: queue
> Yeonkkk: week10
